# enable ferret search engine?
:ferret: true

#image settings
:output_image_jpg_quality: 85
:preprocess_image_resize: 1000x1000
:image_store_format: png
:image_output_format: jpg

#enable wapage caching?
:cache_pages: true

#language settings
:default_language: de
:default_alchemy_language: de
:show_real_root: false
:languages:
    - :language_code: de
      :language: Deutsch
      :frontpage_name: Startseite
      :page_layout: standard
    - :language_code: en
      :language: English
      :frontpage_name: Frontpage
      :page_layout: standard
:translations:
  - :language_code: de
    :language: Deutsch
  - :language_code: en
    :language: English

#contactform settings
:mailer:
  :form_layout_name: contact
  :forward_to_page: false
  :fields:
    - salutation: string
    - firstname: string
    - lastname: string
    - address: string
    - zip: :string
    - city: string
    - phone: string
    - email: string
    - message: text
  :validate_fields:
    :lastname:
      :message: enter_name
    :email:
      :message: enter_email
