- name: article
  display_name: Artikelabsatz
  contents:
  - name: intro
    type: EssenceText
  - name: headline
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: text
    type: EssenceRichtext

- name: intro_image_text
  display_name: Intro-Artikel
  - name: headline
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: text
    type: EssenceRichtext
  
- name: text
  display_name: Text
  contents:
  - name: text
    type: EssenceRichtext

- name: bild
  display_name: Bild
  contents: 
  - name: image
    type: EssencePicture

- name: bild_text
  display_name: Bild und Text
  contents: 
  - name: image
    type: EssencePicture
  - name: text
    type: EssenceRichtext

- name: headline
  display_name: Überschrift
  contents:
  - name: headline
    type: EssenceText

- name: image_mosaic
  display_name: Mosaik
  contents: 
  - name: image
    type: EssencePicture
  - name: caption
    type: EssenceText

- name: footnote
  display_name: Fußnote
  unique: true
  contents:
  - name: note
    type: EssenceRichtext

- name: sitename
  display_name: Webseiten-Name
  unique: true
  contents:
  - name: name
    type: EssenceText

- name: claim
  display_name: Claim
  unique: true
  contents:
  - name: claim
    type: EssenceText

- name: header
  display_name: Header Bild
  unique: true
  contents:
  - name: image
    type: EssencePicture

- name: intro
  display_name: Introtext
  contents: 
  - name: intro
    type: EssenceRichtext

- name: subheadline
  display_name: Zwischenüberschrift
  contents:
  - name: headline
    type: EssenceText

- name: news
  display_name: News
  contents:
  - name: date
    type: EssenceDate
  - name: headline
    type: EssenceText
  - name: body
    type: EssenceRichtext

- name: searchresult
  unique: true
  display_name: Suchergebnis

- name: contactform
  display_name: Kontaktformular
  unique: true
  contents:
  - name: mail_from
    type: EssenceText
  - name: mail_to
    type: EssenceText
  - name: subject
    type: EssenceText
  - name: success_page
    type: EssenceText

- name: newsletter_article
  display_name: Artikel
  contents:
  - name: headline
    type: EssenceText
  - name: text
    type: EssenceRichtext

- name: newsletter_intro
  display_name: Intro
  unique: true
  contents:
  - name: text
    type: EssenceRichtext
